VULNERABILITY_DATABASE = [
    {
        "cpe": "cpe:/a:vsftpd:vsftpd",
        "affected_versions": [{"min": "2.3.4", "max": "2.3.4"}],
        "cve": "CVE-2011-2523",
        "cvss": 10.0,
        "severity": "CRITICAL",
        "title": "vsftpd 2.3.4 Backdoor",
        "description": "A backdoor was introduced into a compromised distribution of vsftpd 2.3.4.",
        "remediation": "Remove the affected installation and deploy a trusted, patched version from a verified source.",
    },
    {
        "cpe": "cpe:/a:apache:http_server",
        "affected_versions": [{"min": "2.2.0", "max": "2.2.32"}],
        "cve": "CVE-2017-7679",
        "cvss": 9.8,
        "severity": "CRITICAL",
        "title": "Apache HTTP Server mod_mime Buffer Over-read",
        "description": "Apache HTTP Server versions in the affected range are vulnerable to a mod_mime buffer over-read condition.",
        "remediation": "Upgrade Apache HTTP Server to a supported and patched release.",
    },
    {
        "cpe": "cpe:/a:apache:http_server",
        "affected_versions": [{"min": "2.0.0", "max": "2.2.31"}],
        "cve": "CVE-2011-3192",
        "cvss": 7.5,
        "severity": "HIGH",
        "title": "Apache HTTP Server Byte Range DoS",
        "description": "Certain Apache HTTP Server versions are affected by a denial-of-service condition in handling overlapping byte-range requests.",
        "remediation": "Upgrade Apache HTTP Server to a supported patched version and apply the vendor's recommended configuration mitigations.",
    },
    {
        "cpe": "cpe:/a:mysql:mysql",
        "match_type": "PACKAGE",
        "fixed_version": "5.0.51a-3ubuntu5.4",
        "cve": "CVE-2008-2079",
        "cvss": 6.8,
        "severity": "MEDIUM",
        "title": "MySQL Security Vulnerability",
        "description": "The detected Ubuntu MySQL package predates the security update associated with this vulnerability.",
        "remediation": "Upgrade the MySQL package to the latest supported security release provided by the operating system vendor.",
    },
    {
        "cpe": "cpe:/a:mysql:mysql",
        "match_type": "PACKAGE",
        "fixed_version": "5.0.51a-3ubuntu5.4",
        "cve": "CVE-2008-3963",
        "cvss": 7.5,
        "severity": "HIGH",
        "title": "MySQL Remote Denial of Service",
        "description": "The detected MySQL package predates the Ubuntu security update addressing this vulnerability.",
        "remediation": "Upgrade MySQL to a supported and patched release.",
    },
    {
        "cpe": "cpe:/a:mysql:mysql",
        "match_type": "PACKAGE",
        "fixed_version": "5.0.51a-3ubuntu5.4",
        "cve": "CVE-2008-4097",
        "cvss": 6.8,
        "severity": "MEDIUM",
        "title": "MySQL Privilege Check Vulnerability",
        "description": "The detected MySQL package predates the Ubuntu security update addressing this privilege-check vulnerability.",
        "remediation": "Upgrade MySQL to a supported and patched release.",
    },
    {
        "cpe": "cpe:/a:mysql:mysql",
        "match_type": "PACKAGE",
        "fixed_version": "5.0.51a-3ubuntu5.4",
        "cve": "CVE-2008-4098",
        "cvss": 5.0,
        "severity": "MEDIUM",
        "title": "MySQL Security Vulnerability",
        "description": "The detected MySQL package predates the Ubuntu security update addressing this vulnerability.",
        "remediation": "Upgrade MySQL to a supported and patched release.",
    },
]
